version: '2'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_INSTALL_PLUGINS=https://grafana.com/api/plugins/jdbranham-diagram-panel/versions/1.6.1/download;diagram-panel,https://grafana.com/api/plugins/grafana-polystat-panel/versions/1.1.0/download;polystat
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - 3000:3000

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command: 
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090

  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080

  loki:
    image: grafana/loki:1.5.0
    #command: -config.file=/etc/loki/local-config.yaml
    command: -config.file=/mnt/config/loki-config.yaml
    volumes:
      - ./loki-config.yaml:/mnt/config/loki-config.yaml
    ports:
      - 3100:3100

  promtail:
    image: grafana/promtail:1.5.0
    #command: -config.file=/etc/promtail/docker-config.yaml
    command: -config.file=/mnt/config/promtail-config.yaml
    volumes:
      - ./promtail-config.yaml:/mnt/config/promtail-config.yaml
      - /var/log:/var/log
    depends_on:
      - loki


volumes:
  grafana_data: {}
  prometheus_data: {}
