apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-ga4
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  ga4-datasource.yaml: |
    apiVersion: 1
    deleteDatasources:
      - name: GA4
        orgId: 1
    datasources:
      - name: GA4
        type: blackcowmoo-googleanalytics-datasource
        access: proxy
        uid: ga4
        isDefault: false
        editable: false
        jsonData:
          authenticationType: jwt
          clientEmail: ${GA4_CLIENT_EMAIL}
          defaultProject: ${GA4_GCP_PROJECT}
          tokenUri: https://oauth2.googleapis.com/token
        secureJsonData:
          privateKey: ${GA4_PRIVATE_KEY}
