apiVersion: v1
kind: ConfigMap
metadata:
  name: yace-prometheus-yet-another-cloudwatch-exporter
  namespace: monitoring
data:
  config.yml: |
    apiVersion: v1alpha1
    discovery:
      jobs:
        - type: AWS/Lambda
          regions: [ap-northeast-2, eu-central-1]
          period: 300
          length: 300
          metrics:
            - name: Invocations
              statistics: [Sum]
            - name: Duration
              statistics: [Average, p50, p99]
            - name: Errors
              statistics: [Sum]
            - name: Throttles
              statistics: [Sum]
            - name: ConcurrentExecutions
              statistics: [Maximum]
        - type: AWS/DynamoDB
          regions: [ap-northeast-2]
          period: 300
          length: 300
          metrics:
            - name: ConsumedReadCapacityUnits
              statistics: [Sum]
            - name: ConsumedWriteCapacityUnits
              statistics: [Sum]
            - name: ReadThrottleEvents
              statistics: [Sum]
            - name: WriteThrottleEvents
              statistics: [Sum]
            - name: SuccessfulRequestLatency
              statistics: [Average, p99]
            - name: SystemErrors
              statistics: [Sum]
            - name: UserErrors
              statistics: [Sum]
        - type: AWS/RUM
          regions: [ap-northeast-2]
          period: 300
          length: 300
          metrics:
            - name: WebVitalsLargestContentfulPaint
              statistics: [Average, p90]
            - name: WebVitalsFirstInputDelay
              statistics: [Average, p90]
            - name: WebVitalsCumulativeLayoutShift
              statistics: [Average, p90]
            - name: JsErrorCount
              statistics: [Sum]
            - name: HttpErrorCount
              statistics: [Sum]
            - name: SessionCount
              statistics: [Sum]
            - name: NavigationFrustratedTransaction
              statistics: [Sum]
            - name: PerformanceNavigationDuration
              statistics: [Average, p95, p99]
